import Head from 'next/head'
import Navbar from '../components/common/Navbar'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar/>
      </nav>

      <main>
        <p>wuejrhjkewr gfuiewr tuirew htuireh uiwerhr tuiowerhuiot h ewruirth uiewrht uierhtuierhtuihewrtuihreuithreuiwht uewrrtheuirw thrueiohtuierht erwui thewriut hiuerwthiuerwh
        </p>
       
      </main>

      <footer >
     
      </footer>
    </div>
  )
}
